### PR TITLE
docker build action follows OHDSI/WebAPI pattern

### PR DESCRIPTION
**Pull request by natb1**
This PR adds a GH action that builds and publishes a docker image whenever there is a [GH release](https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases). The docker build follows the same pattern found in OHDSI/WebApi.

### CODE REVIEW

**Comment by schuemie** [comment]
Nice! 

Would you mind renaming the workflow to something less generic? We may want to have other types of releases in the future (e.g. releases as renv lock files). Maybe `release_docker`?

**Comment by natb1** [comment]
Sure thing, renamed to release_docker

**Review by schuemie — APPROVED** [review]

**Comment by schuemie** [comment]
Thanks!

**Comment by leeevans** [comment]
Thanks @natb1 for developing this GitHub docker build action. It is a significant improvement in the OHDSI build process for maintaining up to date, versioned OHDSI HADES Docker images that will track the latest HADES releases and provide better support for reproducibility!

Thanks @schuemie  for approving this pull request.

**Comment by schuemie** [comment]
Shall I create a release just to trigger the workflow?

**Comment by schuemie** [comment]
I actually just manually triggered the action, so no need to do anything for that, because it seems to already work.

**Comment by natb1** [comment]
Yes, it just [needs a few secrets](https://github.com/OHDSI/Hades/pull/17/files#diff-5a3d232cffae72d86dcf58e80004a18227a654b4fe32f2126d0c78b40dc98741R4) added to the repo. With those it should pass - happy to change it if you guys prefer another way.

**Comment by leeevans** [comment]
@natb1 the following two GitHub secrets are already defined:

DOCKER_HUB_ACCESS_TOKEN
DOCKER_HUB_USERNAME

A secret called GH_TOKEN is also already defined, so I'd appreciate it if you could update the action to rename GITHUBPAT to  GH_TOKEN.

I'm not sure how the DOCKER_IMAGE secret is intended to be used.
I see it referenced in the action here:

      DOCKER_IMAGE: ${{ inputs.docker_image || secrets.DOCKER_IMAGE }}
      
If it's intended to be specific to this HADES Docker action then I would prefer to call the secret HADES_DOCKER_IMAGE. 

It would be great if you could provide an example of the usage of the DOCKER_IMAGE secret.

**Comment by leeevans** [comment]
@natb1 as agreed on our call today, I have created the new OHDSI GitHub secret called HADES_DOCKER_IMAGE. Feel free to submit a new pull request for the github action with the needed secret name changes and we can rerun it

**Comment by natb1** [comment]
Secret names updated here: https://github.com/OHDSI/Hades/pull/18

**Pull request merged**
